### ISSUE TITLE
SNMPv3 parameters in config.yaml

### ISSUE THREAD

**Issue by ldvc** [inexio/thola#68]
Hey! First thing first, thanks for `thola`!

```
% ./thola --version
v0.3.5
```

I would like to set my SNMPv3 parameters in the `config.yaml` file, I tried:

```yaml
device:
  snmp-communities:
  - mycommunity
  snmp-versions:
  - 2c
  - 3
  snmp-v3-auth-key: <redacted>
  snmp-v3-auth-proto: MD5
  snmp-v3-level: "authPriv"
  snmp-v3-priv-key: <redacted>
  snmp-v3-priv-proto: DES
  snmp-v3-user: <redacted>
```
but it didn't work: `Error: invalid request: no SNMP v3 level provided`.

As I'm not very familiar with Golang code, I didn't succeed to spot where the config parsing happen...

Is what I'm trying to do possible? Thanks!
